import React, { createContext, useContext, useState } from "react";

export const T = {
  en: {
    // Sidebar / Nav
    patientPortal: "Patient Portal",
    welcome: "Welcome,",
    patientId: "Patient ID:",
    bookAppt: "Book Appointment",
    bookApptShort: "Book",
    menu: "Menu",
    logout: "Log out",
    nav: {
      home: "Home", appointments: "Appointments", records: "Medical Records",
      prescriptions: "Prescriptions", lab: "Lab Results",
      billing: "Billing", profile: "My Profile",
    },
    // General
    loadingData: "Loading your data…",
    today: "TODAY",
    noUpcoming: "No upcoming appointments.",
    // Home
    upcomingAppts: "Upcoming Appointments",
    upcomingCount: n => `Upcoming Appointments (${n})`,
    statUpcoming: "Upcoming Appts",
    statRecords: "Medical Records",
    statBalance: "Balance Due",
    statPendingLabs: "Pending Labs",
    reminders: "Reminders",
    reminderBalance: bal => `You have an outstanding balance of ${bal}.`,
    reminderRx: n => `${n} prescription(s) awaiting pickup.`,
    reminderLab: n => `${n} lab request(s) still in process.`,
    // Appointments
    allApptsTitle: n => `All Appointments (${n})`,
    noAppts: "No appointments yet.",
    // Records
    recordsTitle: n => `Medical Records (${n})`,
    noRecords: "No medical records yet.",
    noComplaint: "No chief complaint",
    diagnosis: "Diagnosis",
    treatment: "Treatment",
    // Prescriptions
    rxTitle: n => `Prescriptions (${n})`,
    noRx: "No prescriptions yet.",
    // Lab
    labTitle: n => `Lab Results (${n})`,
    noLab: "No lab requests yet.",
    results: "Results",
    // Billing
    totalBillsStat: "Total Bills",
    balanceDueStat: "Balance Due",
    paidBillsStat: "Paid Bills",
    billingTitle: n => `Billing History (${n})`,
    noBills: "No billing records yet.",
    totalLabel: "Total",
    paidLabel: "Paid",
    balanceLabel: "Balance",
    lastLabel: "Last",
    payBtn: "Pay",
    // Profile
    personalInfo: "Personal Information",
    ageLabel: "Age", genderLabel: "Gender",
    bloodTypeLabel: "Blood Type", allergiesLabel: "Allergies",
    contactSection: "Contact",
    phoneLabel: "Phone", emailLabel: "Email", addressLabel: "Address",
    accountSection: "Account",
    registeredLabel: "Registered", lastUpdatedLabel: "Last Updated",
    yearsOld: "years old",
    // Book Appointment Modal
    bookModalTitle: "Book an Appointment",
    stepLabel: (s, t) => `Step ${s} of ${t}`,
    stepDetails: "Details", stepSchedule: "Schedule", stepConfirm: "Confirm",
    apptTypeLabel: "Appointment Type", selectPlaceholder: "Select…",
    doctorLabel: "Doctor",
    complaintLabel: "Chief Complaint / Reason", complaintPlaceholder: "Describe…",
    notesLabel: "Additional Notes (Optional)", notesPlaceholder: "Special requests…",
    dateLabel: "Date", timeLabel: "Time",
    clinicNotice: "Appointment must be confirmed by the clinic.",
    patientLabel: "Patient", reasonLabel: "Reason", notesFieldLabel: "Notes",
    pendingStatus: "Status: Scheduled — awaiting confirmation",
    backBtn: "← Back", nextBtn: "Next →", submitBtn: "Book",
    savingText: "Saving…",
    errType: "Please select appointment type.",
    errDoctor: "Please select a doctor.",
    errReason: "Please enter a reason.",
    errDate: "Please select a date.",
    errPastDate: "Cannot select a past date.",
    errTime: "Please select a time.",
    errSave: "Could not save. Please try again.",
    apptBookedTitle: "Appointment Booked!",
    apptBookedMsg: (type, date, time) => `${type} on ${date} — ${time}`,
    // Pay Bill Modal
    payModalTitle: "Pay Bill",
    billIdLabel: "Bill ID:",
    totalBillLabel: "Total Bill",
    amountPaidLabel: "Amount Paid",
    balanceRemLabel: "Balance",
    payAmountLabel: "Payment Amount",
    payMethodLabel: "Payment Method",
    cancelBtn: "Cancel",
    payNowBtn: "Pay Now",
    processingText: "Processing…",
    fullBtn: "Full",
    errPayAmount: "Please enter a valid amount.",
    errPayMax: max => `Maximum payable: ${max}`,
    errPaySave: "Could not save. Please try again.",
    paySuccessMsg: (amt, method, status) => `${amt} paid via ${method}. Status: ${status}`,
  },

  tl: {
    patientPortal: "Patient Portal",
    welcome: "Maligayang pagdating,",
    patientId: "Patient ID:",
    bookAppt: "Mag-book ng Appointment",
    bookApptShort: "Mag-book",
    menu: "Menu",
    logout: "Mag-logout",
    nav: {
      home: "Home", appointments: "Mga Appointment", records: "Medical Records",
      prescriptions: "Mga Reseta", lab: "Lab Results",
      billing: "Bayarin", profile: "Aking Profile",
    },
    loadingData: "Naglo-load ng iyong data…",
    today: "NGAYON",
    noUpcoming: "Wala pang upcoming.",
    upcomingAppts: "Susunod na Appointment",
    upcomingCount: n => `Susunod na Appointment (${n})`,
    statUpcoming: "Upcoming Appts",
    statRecords: "Medical Records",
    statBalance: "Natitirang Bayad",
    statPendingLabs: "Pending Labs",
    reminders: "Mga Paalala",
    reminderBalance: bal => `Mayroon kang natitirang bayad na ${bal}.`,
    reminderRx: n => `${n} prescription ang naghihintay.`,
    reminderLab: n => `${n} lab request ang in-process pa.`,
    allApptsTitle: n => `Lahat ng Appointments (${n})`,
    noAppts: "Wala pang appointments.",
    recordsTitle: n => `Medical Records (${n})`,
    noRecords: "Wala pang medical records.",
    noComplaint: "Walang chief complaint",
    diagnosis: "Diagnosis",
    treatment: "Paggamot",
    rxTitle: n => `Mga Reseta (${n})`,
    noRx: "Wala pang prescriptions.",
    labTitle: n => `Lab Results (${n})`,
    noLab: "Wala pang lab requests.",
    results: "Resulta",
    totalBillsStat: "Lahat ng Bills",
    balanceDueStat: "Natitirang Bayad",
    paidBillsStat: "Nabayaran",
    billingTitle: n => `Kasaysayan ng Bayarin (${n})`,
    noBills: "Wala pang billing records.",
    totalLabel: "Kabuuan",
    paidLabel: "Nabayad",
    balanceLabel: "Natitira",
    lastLabel: "Huli",
    payBtn: "Bayad",
    personalInfo: "Personal na Impormasyon",
    ageLabel: "Edad", genderLabel: "Kasarian",
    bloodTypeLabel: "Uri ng Dugo", allergiesLabel: "Mga Allergy",
    contactSection: "Kontak",
    phoneLabel: "Telepono", emailLabel: "Email", addressLabel: "Tirahan",
    accountSection: "Account",
    registeredLabel: "Nag-register", lastUpdatedLabel: "Huling na-update",
    yearsOld: "taong gulang",
    bookModalTitle: "Mag-book ng Appointment",
    stepLabel: (s, t) => `Hakbang ${s} ng ${t}`,
    stepDetails: "Detalye", stepSchedule: "Oras & Petsa", stepConfirm: "Kumpirma",
    apptTypeLabel: "Uri ng Appointment", selectPlaceholder: "Piliin…",
    doctorLabel: "Doktor",
    complaintLabel: "Dahilan / Chief Complaint", complaintPlaceholder: "Ilarawan…",
    notesLabel: "Karagdagang Tala (Optional)", notesPlaceholder: "Espesyal na kahilingan…",
    dateLabel: "Petsa", timeLabel: "Oras",
    clinicNotice: "Ang appointment ay kailangang kumpirmahin ng klinika.",
    patientLabel: "Pasyente", reasonLabel: "Dahilan", notesFieldLabel: "Tala",
    pendingStatus: "Status: Scheduled — naghihintay sa kumpirmasyon",
    backBtn: "← Bumalik", nextBtn: "Susunod →", submitBtn: "I-book",
    savingText: "Nag-sa-save…",
    errType: "Piliin ang uri ng appointment.",
    errDoctor: "Piliin ang doktor.",
    errReason: "Ilagay ang dahilan.",
    errDate: "Piliin ang petsa.",
    errPastDate: "Hindi pwede ang nakaraang petsa.",
    errTime: "Piliin ang oras.",
    errSave: "Hindi ma-save. Subukan ulit.",
    apptBookedTitle: "Appointment Booked!",
    apptBookedMsg: (type, date, time) => `${type} sa ${date} — ${time}`,
    payModalTitle: "Bayad ng Bill",
    billIdLabel: "Bill ID:",
    totalBillLabel: "Kabuuang Bill",
    amountPaidLabel: "Naibayad na",
    balanceRemLabel: "Natitira",
    payAmountLabel: "Halaga ng Bayad",
    payMethodLabel: "Paraan ng Bayad",
    cancelBtn: "Kanselahin",
    payNowBtn: "Bayaran ngayon",
    processingText: "Nagpo-proseso…",
    fullBtn: "Buo",
    errPayAmount: "Ilagay ang tamang halaga.",
    errPayMax: max => `Maximum na mababayaran: ${max}`,
    errPaySave: "Hindi ma-save. Subukan ulit.",
    paySuccessMsg: (amt, method, status) => `${amt} nabayaran via ${method}. Status: ${status}`,
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem("lang") || "en");
  const switchLang = () => {
    const next = lang === "en" ? "tl" : "en";
    setLang(next);
    localStorage.setItem("lang", next);
  };
  return (
    <LanguageContext.Provider value={{ lang, t: T[lang], switchLang }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLang = () => useContext(LanguageContext);